---
- hosts: all
  become: true
  roles:
    - role: proxmox_vm
      vars:
        vm_template_vmid: 8201  # kubernetes-ready template
        vm_nameserver: "192.168.178.1"
        vm_gateway: "192.168.178.1"
        vm_user: "root"

        proxmox_vms:
          - vmid: 9001
            name: "k8s-master-01"
            memory: 4096
            cores: 4
            disk_size: "50G"
            ip: "192.168.178.215"
            cidr: 24
            tags:
              - kubernetes
              - master
