- hosts: all
  become: True
  roles:
    - role: mrlesmithjr.zfs
      vars:
        zfs_install_update: true

        # Pools erstellen
        zfs_create_pools: true

        # Keine Filesystems / Volumes anlegen
        zfs_create_filesystems: false
        zfs_create_volumes: false

        # Pools Übersicht
        zfs_pools:
          # K8s Pool mit 2 Mirror VDEVs (Striped Mirror)
          - name: zpool_k8s
            action: create
            type: mirror
            devices:
              - "ata-Samsung_SSD_860_EVO_500GB_S4XBNF0NA06663B"
              - "ata-Samsung_SSD_860_EVO_500GB_S4XBNF0NA07832N"
            compression: lz4
            recordsize: 16k
            atime: off
            xattr: sa
            mountpoint: /mnt/zpool_k8s
            state: present

          - name: zpool_k8s
            action: add
            type: mirror
            devices:
              - "ata-Samsung_SSD_870_EVO_500GB_S6PYNL0XB10079K"
              - "ata-Samsung_SSD_870_EVO_500GB_S6PYNL0XB10080A"
            state: present

          # NVMe Pool (single device)
          - name: zpool_nvme
            action: create
            type: basic
            devices:
              - "nvme-SSD_M.2_PCIe3_1TB_InnovationIT_704822210300255"
            compression: lz4
            recordsize: 16k
            atime: off
            mountpoint: /mnt/zpool_nvme
            state: present

          # Backup Pool (single HDD)
          - name: zpool_backup
            action: create
            type: basic
            devices:
              - "ata-ST2000DM001-1ER164_W4Z2B3JZ"
            compression: lz4
            recordsize: 128k
            atime: off
            mountpoint: /mnt/zpool_backup
            state: present

        # Optional: Performance Tuning (kann bleiben oder angepasst werden)
        zfs_enable_performance_tuning: true
