---
- hosts: all
  become: true
  roles:
    - role: proxmox_cloudinit_template
      vars:
        cloudinit_storage: "vms"
        cloudinit_storage_path: "/mnt/zpool_nvme"
        cloudinit_user: "root"

        cloudinit_templates:
          - vmid: 8200
            name: "ubuntu-noble-template"
            image_url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
            checksum_url: "https://cloud-images.ubuntu.com/noble/current/SHA256SUMS"
            tags:
              - ubuntu-template
              - noble
              - cloudinit
            vendor_data: |
              #cloud-config
              runcmd:
                - apt-get update
                - apt-get install -y qemu-guest-agent
                - systemctl enable ssh
                - reboot

          - vmid: 8202
            name: "ubuntu-noble-template-nvidia-runtime"
            image_url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
            checksum_url: "https://cloud-images.ubuntu.com/noble/current/SHA256SUMS"
            tags:
              - ubuntu-template
              - noble
              - cloudinit
              - nvidia
            vendor_data: |
              #cloud-config
              runcmd:
                - curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
                - curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
                - apt-get update
                - apt-get install -y qemu-guest-agent nvidia-dkms-550-server nvidia-utils-550-server nvidia-container-runtime
                - systemctl enable ssh
                - reboot
